<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework Condition="'$(MusicMicTargetFramework)' == ''">net10.0</TargetFramework>
    <TargetFramework Condition="'$(MusicMicTargetFramework)' != ''">$(MusicMicTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
